README.md
Not sure if Zero Waste is the best section for this - or whether to use the 🇺🇸 flag.  Moment is based in the US, but I couldn't find anything saying where their products are manufactured.
=> [suggest] Add Moment Bio Case for iphone

README.md
Another carbon offsetting option for Germany.
=> Added atmosfair

README.md
- Moved products out of the zero waste section into the sustainable lifestyle section
- Added Too good to go: sell food waste
- Added Sparkmeter: Humanitarian smart energy metering solution that purchases wasted unused electricity from utilities and resells it to hard-to-reach places and underserved markets, thus reducing overall energy consumption.
- Ecocina rocket stoves, StoveTeam, and Aprovecho Research Center - Orgs working together to test and improve wood-fired cook stove designs to reduce deforestation, emissions, and improve health in third world countries.
- Sun Oven: Insulated solar food cooker
- Lehmans: One-stop shop for non-electric, homesteading, survival, handmade, Amish made, plastic free, durable, quality goods.  If you envision switching to live a simpler life, this …
=> Moar awesomeness

README.md
Thank you for publishing this great list! I'm one of the founders of [AirCare](https://air.care/) and we would be honored to be included. We've developed what we think is the easiest way to understand and compensate for the environmental impact of air travel. We have some really great features in the pipeline that we believe can have a huge positive impact.
=> Adding AirCare

package-lock.json, package.json, src/countries.js, src/data/links.yaml, src/pages/index.jsx
This way we can easily filter by country, etc.
Notes:
- I called the field `countries` instead of `availability`
because availability can mean a lot of things.
- I left a few `icon` fields in place that didn't seem to be
about geography.
- (They're not displayed, I just don't want to delete any data.)
- I put country names in a `title` attribute so if you're curious
what flag that is you can just mouse over it (on desktop).
Closes #17.
=> Converted country info to ISO codes.

README.md, src/data/categories.yaml, src/data/links.yaml
Energy Category Description Updated, 3 Energy Links Added, README Updated Accordingly.
=> Energy Updates

README.md
Added new section for recycled apparel and moved/added some resources. Added another option of a compostable phone case.
Maybe would be better as a subsection under Lifestyle
=> New section and products

README.md
Added Droneseed & Land Life Company to the Reforestation category.
=> Added 2 companies to the Reforestation category

src/styles/global.scss
I thought it may be beneficial to the user experience if the website looks less rigid. These minor animations should aid the user in experiencing the website a bit more interactive.
=> Added some animations for a better user experience

.prettierrc, .vscode/launch.json, LICENSE, README.md, gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/data/categories.yaml, src/pages/index.jsx, src/templates/category.jsx
closes #16
simple category pages, which for now are pretty much a duplication of
content on index page. Fine for now, just trying to get the functionality
there.
=> Category Pages

src/data/links.yaml
=> Added WeForest project

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/components/carousel.jsx, src/components/seo.jsx, src/data/links.yaml, src/pages/index.jsx, src/templates/category.jsx
This PR adds an SEO component that can be added to any page in order to set SEO properties/meta tags for that page. The component is powered by [gatsby-plugin-react-helmet](https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet/).
The component has been added to the home page and the category pages. Some of the props have been purposely left empty, you can fill them in as you like.
```javascript
<SEO 
title="Home"
description="Welcome to the website"
keywords={[`my`, `seo`, `keywords`]}
meta={[
{
name: 'author',
content: 'Stephen Samra'
}
]}
image="https://avatars3.githubusercontent.com/u/8583469?s=460&v=4"
/>
```
The above component would result in the following HTML being rendered in the `<head>` of the page:
```html
<title>Home | Awesome.Earth</title>
<meta name="description" …
```
=> Add an SEO component

src/data/links.yaml
I just heard about this site from [Tom Scott's most recent YouTube video](https://youtu.be/l1Jb-IM99j8?t=30), which he also blogged about [here](https://www.tomscott.com/carbon/). I immediately thought of your site, and didn't see this linked already, hence this PR.
I've not researched Gold Standard on my own beyond skimming it enough to write up the brief description; however, I've seen enough of Tom's videos to know that he does his homework. Good enough for me!
=> Add link for Gold Standard (carbon offsetting)

src/data/links.yaml
I'd like to help to extend the list, so I made this PR about an amazing phone app to avoid food wasting.
=> Add Too good to go

src/components/carousel.jsx, src/components/layout.jsx, src/pages/index.jsx, src/styles/global.scss, src/templates/category.jsx
=> Shared layout

README.md
One Brazilian startup that incentive user to change vehicles that emit CO2 for another that not do that and generate one crypto coin for this users.
=> Add GreenMovi

src/data/links.yaml
Added links to a green credit card from an independent dutch bank and shoes+clothes made from recycled plastic (ocean)
=> Green credit card and shoes from plastic waste

src/data/links.yaml
Awesome project to gather evidence of climate change using spare computing power
=> Added ClimatePrediction.net

package.json, src/components/layout.jsx, src/pages/index.jsx, src/styles/global.scss, src/templates/category.jsx
Reverts philsturgeon/awesome-earth#90
=> Revert "[Redesign] Category page structure / nav updates"

src/data/links.yaml
[Cariuma](https://cariuma.com/pages/about-us) makes some swell sustainable shoes.  More information can be found in [this article](https://www.fastcompany.com/90418251/these-shoes-are-made-from-bamboo-sugar-cane-and-cork-and-totally-carbon-neutral).
=> Add cariuma to sustainable lifestyle

gatsby-node.js, src/categories/carbon-reduction.md, src/categories/cooking.md, src/categories/documentaries.md, src/categories/home-improvements.md, src/categories/news.md, src/categories/politics.md, src/categories/reforestation.md, src/categories/renewable-energy.md, src/categories/sustainable-lifestyle.md, src/categories/transportation.md, src/categories/travel.md, src/categories/volunteering.md, src/categories/zero-waste.md, src/components/CategoryCard.jsx, src/data/links.yaml, src/pages/index.jsx, src/templates/category.jsx
Adds an `intro` key to the category front-matter which will be displayed on the homepage and used as the SEO description:
Resolves #80
=> Category Descriptions

src/data/links.yaml
Reverts philsturgeon/awesome-earth#113
=> Revert "Update Links “links”"

src/data/links.yaml
Simple, fun and customizable app to help you reduce meat in your alimentation.
=> Add No Meat Today

src/data/links.yaml
App that helps people make good choices when buying seafood
=> Add seafood watch

src/templates/category.jsx, src/templates/tag.jsx
Fixes #128 
category page:
tag page:
=> Sort links on title and category pages

package-lock.json, src/components/RecentLinkItem.jsx, src/components/RecentLinks.jsx, src/components/index.js, src/pages/index.jsx
Addresses #118
GraphQL query updated.
RecentLinks component added. Prop for amount of recent items to display.
Added the compoenent to the homepage.
@philsturgeon should I add tags as badges?
Preview picture:
=> Adds RecentLinks to homepage.

src/components/MailingListForm.jsx
lint was yelling about this, so I restructured the tiny letter form submit
=> Clean up mailing list form markup

src/categories/jobs.md, src/data/links.yaml
=> Add jobs category, image and relevant links

src/data/links.yaml
Combining links from https://github.com/timothyclifford/planet-earth
Will add more over the week.
Let me know if you think any aren't relevant.
=> Combine with planet earth

README.md
Follows https://github.com/philsturgeon/awesome-earth/issues/166#issuecomment-649852292.
=> Add note about protect.earth

README.md
from 8k to 80k in line with site name
=> 8000 Hours->80,000 hours

README.md
4ocean is an awesome shop where you can buy great stuff. Doing so you support cleaning the coastlines from plastic pollution.
=> Add 4ocean to clothing section

README.md
Here I have added another zero water waste purifier which uses rejected water as well.
=> Added Zero Water Waste Technology

README.md
Adding diversity for source of content from Asia
=> Added Green Pulse from Singapore

README.md
Please add the label "**hacktoberfest-accepted**" on the right screen.
Added [Climate Reality](https://climaterealityproject.org/) in the politics listing. It is an initiative of former United States vice president and 2007 Nobel Peace Prize laureate Al Gore to make urgent action a necessity to address climate change issues through activism and cutting greenhouse gas emissions.
=> Added Climate Reality in the politics listing

README.md
I discovered ecotalk earlier and thought it sounded perfect for this list. I wasn't sure where to add it so I created a new section.
=> Adding ecotalk

README.md
URL: https://climatetriage.com/
Discover a meaningful way to contribute to open source projects focused on climate technology and sustainability.
Harness the power of open source collaboration to tackle environmental challenges such as climate change, clean energy, biodiversity, and natural resource conservation. ClimateTriage brings you all the impactful projects that welcome new developers with Help Wanted and Good First Issues. Whether you're an experienced developer, a scientist, or a newcomer looking to contribute, we'll connect you with opportunities to use your skills to create a sustainable future.
=> Add ClimateTriage

README.md
Update NoFoodWasted url to toogootogo
=> Update NoFoodWasted url to toogootogo
